CREATE TABLE citations (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  citation_type TEXT NOT NULL,
  address TEXT,
  author TEXT,
  booktitle TEXT,
  edition TEXT,
  editor TEXT,
  howpublished TEXT,
  journal TEXT,
  month TEXT,
  note TEXT,
  number INTEGER,
  organization TEXT,
  pages TEXT,
  publisher TEXT,
  school TEXT,
  series TEXT,
  title TEXT,
  type TEXT,
  volume FLOAT,
  year INTEGER
);
